#!/usr/bin/python3
import mysql.connector as mysql
import cgi
import subprocess
from http import cookies
# RDS information
username='root'
password='vijay'
database_name='project1'
host='localhost'
ip=subprocess.getoutput("curl http://169.254.169.254/latest/meta-data/public-ipv4")
ip=ip.split('\n')[-1]

# Now connecting the Database
conn=mysql.connect(user=username,password=password,database=database_name,host=host)

# Now generating a SQL language cursor 
cur = conn.cursor()

# gat value from form
form = cgi.FieldStorage()
user_email =form.getvalue('email')
user_password = form.getvalue('password')

#let's check if password is correct
cur.execute("select * from userInfo where user_email='"+user_email+"'")
data=cur.fetchone()
#user data is incorrect
if len(data)==0 or data[-1]!=user_password:
	print("Content-type: text/html\r\n\r\n")
	print('<!DOCTYPE html><html><body bgcolor="#000000"><center><img src="http://'+ip+'/img/giphy.gif"></img>')
	print('<h1><font color="#8ebf42" face="verdana">Invalid Email aur Password</font></h1>')
	print('<meta http-equiv = "refresh" content = "3; url = http://'+ip+'/login-register" />')
	print("</center></body></html>")
	exit(0)


#User exist now lets create cookie and redirect this user to quiz Board webpage
c=cookies.SimpleCookie()
c['User_Name']=data[1]+" "+data[2]
c['User_Name']['path']='/'
c['Email']=data[3]
c['Email']['path']='/'
c['User_Id']=data[0]
c['User_Id']['path']='/'

print(c)

#print The magic line
print('Content-type: text/html \r\n\r\n')

#Now Cookies are set and we can use them now 

print('<!DOCTYPE html><html><body bgcolor="#000000"><center><img src="http://'+ip+'/img/giphy.gif"></img>')
print('<h1><font color="#8ebf42" face="verdana">Login Succesfull</font></h1>')
print('<meta http-equiv = "refresh" content = "3; url = http://'+ip+'/" />')
print("</center></body></html>")
