#!/usr/bin/python3
import mysql.connector as mysql
import cgi
from http import cookies
# RDS information
username='root'
password='vijay'
database_name='project1'
host='localhost'

# Now connecting the Database
conn=mysql.connect(user=username,password=password,database=database_name,host=host)

# Now generating a SQL language cursor 
cur = conn.cursor()

# gat value from form
form = cgi.FieldStorage()

user_email =form.getvalue('email')
user_password = form.getvalue('password')

basic='''
<!DOCTYPE html><html>
<head><title>Login</title>
<link href="/img/favicon.png" rel="icon">
<link href="/img/apple-touch-icon.png" rel="apple-touch-icon">
<script>
document.onkeydown = function(e) {
			if(event.keyCode == 123) {
			return false;
			}
			if(e.ctrlKey && e.shiftKey && e.keyCode == 'I'.charCodeAt(0)){
			return false;
			}
			if(e.ctrlKey && e.shiftKey && e.keyCode == 'J'.charCodeAt(0)){
			return false;
			}
			if(e.ctrlKey && e.keyCode == 'U'.charCodeAt(0)){
			return false;
			}
			
			}
</script>  
</head>
<body  oncontextmenu="return false;" bgcolor="#000000"><center><img src="/img/giphy.gif"></img>
'''

if user_email==None or user_password==None:
	print("Content-type: text/html\r\n\r\n") # Magic line
	print(basic)
	print('<h1><font color="#03fca9" face="verdana">No Input Given</font></h1>')
	print('<meta http-equiv = "refresh" content = "3; url = /login-register" />')
	print("</center></body></html>")
	exit(0)

#let's check if password is correct
cur.execute("select * from userInfo where user_email='"+user_email+"'")
data=cur.fetchone()
#user data is incorrect
if data==None or data[-1]!=user_password:
	print("Content-type: text/html\r\n\r\n") # Magic line
	print(basic)
	print('<h1><font color="#03fca9" face="verdana">Invalid Credentials</font></h1>')
	print('<meta http-equiv = "refresh" content = "3; url = /login-register" />')
	print("</center></body></html>")
	exit(0)


#User exist now lets create cookie and redirect this user to quiz Board webpage
c=cookies.SimpleCookie()
c['User_Name']=data[1]+" "+data[2]
c['User_Name']['path']='/'
c['Email']=data[3]
c['Email']['path']='/'
c['User_Id']=data[0]
c['User_Id']['path']='/'

if user_email=="root@linux.com":
	c['sKey']='RqEtSkwaLw'
	c['sKey']['path']='/cgi-bin/'
 
print(c)

#Now Cookies are set and we can use them now 
print("Content-type: text/html\r\n\r\n") # Magic line
print(basic)
print('<h1><font color="#03fca9" face="verdana">Login Succesfull</font></h1>')
print('<meta http-equiv = "refresh" content = "3; url = /cgi-bin/homepage#board" />')
print("</center></body></html>")
