#!/usr/bin/python3
import mysql.connector as mysql
import cgi

#RDS information
username='root'
password='vijay'
database_name='project1'
host='localhost'

print("Content-type: text/html\r\n\r\n")
# Now connecting the Database
conn=mysql.connect(user=username,password=password,database=database_name,host=host)

# Now generating a SQL language cursor 
cur = conn.cursor()

# gat value from form
form = cgi.FieldStorage()
first_name = form.getvalue('firstname')
last_name = form.getvalue('lastname')
user_email =form.getvalue('email')
mobile =form.getvalue('phone')
user_password = form.getvalue('password')

print('<!DOCTYPE html><html><body bgcolor="#000000"><center><img src="/img/giphy.gif"></img>')
#let's check if user is already register
cur.execute("select user_email from userInfo where user_email='"+user_email+"'")
ch=[i for i in cur]
if len(ch)==1:
	print('<h1><font color="#8ebf42" face="verdana">Already Register email</font></h1>')
	print('<meta http-equiv = "refresh" content = "3; url = /login-register" />')
	print("</center></body></html>")
	exit(0)

# insert
sql = "INSERT INTO userInfo (user_first_name, user_last_name, user_email, user_phone, user_password) VALUES (%s, %s, %s, %s, %s)"
val = (first_name,last_name,user_email,mobile,user_password)

cur.execute(sql, val)

conn.commit()    
# closing connection
conn.close()

print('<h1><font color="#8ebf42" face="verdana">Registration Succesfull,Now you can login</font></h1>')
print('<meta http-equiv = "refresh" content = "3; url = /login-register" />')
print("</center></body></html>")
